
name: Testing
on:
  push: 
      branches:
        - main
  workflow_dispatch:
 
jobs: 
  j1: 
    runs-on: "ubuntu-latest"
    steps:
      - name: "Step 1"
        run: 'echo \"Running step 111\"'

      - name: "Step 2"
        run: 'echo \"Running step 111\"'
  

