name: Deploy to GH Pages
on:
  push:
    branches:
      - main
    paths:
      - index.html
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Push to pages branch
        run: |
          git add .
          git commit -m "Index page updated"
          git push -f origin main:pages

