name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "hello world"
        shell: bash
jobs:
  goodbye:
    runs-on: ubuntu-latest
    steps:
